[tools]
"gem:kamal" = "latest"
php = "8.4"
ruby = "latest"

[env]
_.file = ".env"

[tasks.deploy]
description = "Deploy the app with database (idempotent)"
run = [
    "echo 'Ensuring database is running...'",
    "kamal accessory boot db || echo 'Database already running'",
    "echo 'Deploying application...'",
    "kamal deploy"
]

[tasks.migrate]
description = "Run database migrations on deployed app"
run = [
    "echo 'Running database migrations...'",
    "kamal app exec --interactive 'php artisan migrate --force'"
]

[tasks.sync]
description = "Manually sync the Airtable"
run = [
    "echo 'Syncing Airtable...'",
    "kamal app exec --interactive 'env LOG_CHANNEL=stderr LOG_LEVEL=info php artisan sync:tables'"
]

