[tools]
"gem:kamal" = "latest"
php = "8.4"
ruby = "latest"

[env]
_.file = ".env"

[tasks.deploy]
description = "Deploy the app with database (idempotent)"
run = [
    "echo 'Ensuring database is running...'",
    "kamal accessory boot db || echo 'Database already running'",
    "echo 'Deploying application...'",
    "kamal deploy"
]

[tasks.migrate]
description = "Run database migrations on deployed app"
run = [
    "echo 'Running database migrations...'",
    "curl -f https://hymn.dk/migrate || echo 'Migration failed, trying via web route'",
    "curl -f https://hymn.dk/fix-migration-state || echo 'Alternative migration approach failed'"
]
