service: ctfg
image: jchillerup/ctfg
servers:
  web:
    - 51.68.47.136
proxy:
  ssl: true
  hosts:
    - connectingcurrent.tech
    - connectingcurrenttech.com
    - connectingcurrenttech.org
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: jchillerup
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  clear:
    DB_HOST: ctfg-db
    DB_PORT: 3306
    DB_DATABASE: ctfg
    DB_USERNAME: ctfg
    APP_ENV: production
    APP_DEBUG: true
    LOG_CHANNEL: single
  secret:
    - MYSQL_PASSWORD
    - DB_PASSWORD
    - APP_KEY
    - AIRTABLE_BASE
    - AIRTABLE_KEY

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  db:
    image: mariadb:10.11
    host: 51.68.47.136
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: ctfg
        MYSQL_USER: ctfg
      secret:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_PASSWORD
    directories:
      - data:/var/lib/mysql

  scheduler:
    image: ghcr.io/jchillerup/ctfg
    host: 51.68.47.136
    cmd: php artisan schedule:work
    env:
      clear:
        DB_HOST: ctfg-db
        DB_PORT: 3306
        DB_DATABASE: ctfg
        DB_USERNAME: ctfg
        APP_ENV: production
        APP_DEBUG: true
        LOG_CHANNEL: single
      secret:
        - MYSQL_PASSWORD
        - DB_PASSWORD
        - APP_KEY
        - AIRTABLE_BASE
        - AIRTABLE_KEY
