# Name of your application. Used to uniquely configure containers.
service: ctfg

# Name of the container image.
image: jchillerup/ctfg

# Deploy to these servers.
servers:
  web:
    - 49.12.97.157
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: hymn.dk

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: jchillerup

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    DB_HOST: ctfg-db
    DB_PORT: 3306
    DB_DATABASE: ctfg
    DB_USERNAME: ctfg
    APP_ENV: production  
    APP_DEBUG: true
    LOG_CHANNEL: single
  secret:
    - MYSQL_PASSWORD
    - DB_PASSWORD
    - APP_KEY
    - AIRTABLE_BASE
    - AIRTABLE_KEY

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
#
# aliases:
#   shell: app exec --interactive --reuse "bash"

# Use a different ssh user than root
#
# ssh:
#   user: app

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
accessories:
  db:
    image: mariadb:10.11
    host: 49.12.97.157
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: ctfg
        MYSQL_USER: ctfg
      secret:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_PASSWORD
    directories:
      - data:/var/lib/mysql
  
  scheduler:
    image: jchillerup/ctfg
    host: 49.12.97.157
    cmd: php artisan schedule:work
    env:
      clear:
        DB_HOST: ctfg-db
        DB_PORT: 3306
        DB_DATABASE: ctfg
        DB_USERNAME: ctfg
        APP_ENV: production  
        APP_DEBUG: true
        LOG_CHANNEL: single
      secret:
        - MYSQL_PASSWORD
        - DB_PASSWORD
        - APP_KEY
        - AIRTABLE_BASE
        - AIRTABLE_KEY
